modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
# issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="krtscp"
version="${file.jarVersion}"
displayName="Kuart's SCPs"
# logoFile="krtscp.png"
authors="Kuart"
displayTest="MATCH_VERSION"
description='''SCPs added to newer versions of Minecraft, will have addons for other mods'''

[[dependencies.krtscp]]
    modId="forge"
    mandatory=true
    versionRange="[43.3.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.krtscp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
